name: Continuous Delivery

env:
    AWS_REGION: eu-north-1
    EBS_APP_NAME: lime-dev
    ENVIRONMENT: development

on:
    push:
        branches:
            - development
    workflow_dispatch:

concurrency:
    group: ${{ github.ref_name }}
    cancel-in-progress: false

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Release
              id: release
              uses: google-github-actions/release-please-action@v4
              with:
                  manifest-file: .release-please-manifest.json
                  config-file: release-please-config.json
                  release-type: node

    deploy:
        name: Deploy
        needs: release
        if: ${{ needs.release.outputs.release_created }}
        runs-on: ubuntu-latest
        environment:
            name: development
            url: http://lime.eu-north-1.elasticbeanstalk.com

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc

            - name: Prepare deployment package
              run: |
                  zip -r build.zip . -x .github

            - name: Deploy to Beanstalk
              uses: einaregilsson/beanstalk-deploy@v21
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                  region: ${{ env.AWS_REGION }}
                  application_name: ${{ env.EBS_APP_NAME }}
                  environment_name: ${{ env.ENVIRONMENT }}
                  version_label: ${{ github.sha }}
                  deployment_package: ./build.zip
